### ISSUE TITLE
Add blog posts as markdown files support (like Jekyll)

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/athityakumar.github.io#15]
# Preference 

Each blog post file should be added as a `.yml` (YAML) format with a structure similar to the one given below. No more need for extra fields like `hyperlinks` /  `images`. Store disqus keys in a single separate file.

```YAML
Timestamp:	dd/mm/yyyy hh:mm

Title:	An apt title

Description:	A good description which is short enough to be a preview when shared on Facebook. 

Tags: 
    -   8
    -   10

Image preview:	image.png

Content:   |
    --- Divider ---
    
     _How are you_ *bold*

    :heart:
```

# How to proceed

First of all, `yaml` gem will parse this `.yml` file. Next, the `html` key of this file will be parsed by `redcarpet` gem, to give a html translated string. Further, this string should be tweaked with additional features to fit the Semantic-UI template. Also, [gh-emojis](https://github.com/zzarcon/gh-emoji) js library can be used to render the markdown emojis on the website.

For, example, `--- X ---` in markdown should be translated as a `divider` element in HTML. The `[text](link)` should be tweaked to open in a new tab. Also, `!(image.png)` should have ability to have css classes.
